// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "post": {
                "description": "Crea un nuevo usuario en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Crear nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerCreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerCreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Inicia sesión con usuario y contraseña",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticación"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerLoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/login/verify": {
            "post": {
                "description": "Verifica el código de autenticación en dos pasos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticación"
                ],
                "summary": "Verificar código de dos pasos",
                "parameters": [
                    {
                        "description": "Datos de verificación",
                        "name": "verification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerVerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerVerifyCodeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/password/reset": {
            "post": {
                "description": "Restablece la contraseña usando el código de verificación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contraseña"
                ],
                "summary": "Restablecer contraseña",
                "parameters": [
                    {
                        "description": "Datos de restablecimiento",
                        "name": "reset",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/password/reset/request": {
            "post": {
                "description": "Envía un código de verificación al correo para restablecer la contraseña",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contraseña"
                ],
                "summary": "Solicitar restablecimiento de contraseña",
                "parameters": [
                    {
                        "description": "Correo electrónico",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerPasswordResetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerPasswordResetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/profile/2fa/toggle": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Activa o desactiva la verificación en dos pasos para el usuario",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "seguridad"
                ],
                "summary": "Activar/desactivar verificación en dos pasos",
                "parameters": [
                    {
                        "description": "Estado de verificación",
                        "name": "toggle",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerToggleTwoFactorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerToggleTwoFactorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/profile/password/change": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Cambia la contraseña usando el código de verificación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contraseña"
                ],
                "summary": "Cambiar contraseña",
                "parameters": [
                    {
                        "description": "Datos de cambio",
                        "name": "change",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerResetPasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/profile/password/change/request": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Envía un código de verificación para cambiar la contraseña",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contraseña"
                ],
                "summary": "Solicitar cambio de contraseña",
                "parameters": [
                    {
                        "description": "Datos de cambio",
                        "name": "change",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerChangePasswordResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entities.SwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.SwaggerChangePasswordRequest": {
            "type": "object",
            "properties": {
                "current_password": {
                    "type": "string",
                    "example": "ContraseñaActual123"
                }
            }
        },
        "entities.SwaggerChangePasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Código de verificación enviado"
                }
            }
        },
        "entities.SwaggerCreateUserRequest": {
            "type": "object",
            "properties": {
                "apellidos": {
                    "description": "Apellidos del usuario",
                    "type": "string",
                    "example": "Martínez García"
                },
                "contrasena": {
                    "description": "Contraseña (mínimo 8 caracteres, debe incluir mayúsculas, minúsculas y números)",
                    "type": "string",
                    "example": "Abc123*"
                },
                "correo_electronico": {
                    "description": "Correo electrónico",
                    "type": "string",
                    "example": "rodrigo.martinez@empresa.com"
                },
                "nombres": {
                    "description": "Nombres del usuario",
                    "type": "string",
                    "example": "Rodrigo Antonio"
                },
                "rol": {
                    "description": "Rol del usuario (administrador, apicultor, tecnico)",
                    "type": "string",
                    "enum": [
                        "administrador",
                        "apicultor",
                        "tecnico"
                    ],
                    "example": "apicultor"
                },
                "usuario": {
                    "description": "Nombre de usuario (sin espacios, solo letras, números y puntos)",
                    "type": "string",
                    "example": "rodrigo.martinez"
                }
            }
        },
        "entities.SwaggerCreateUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensaje informativo",
                    "type": "string",
                    "example": "Usuario creado exitosamente. Se ha enviado un correo de bienvenida."
                }
            }
        },
        "entities.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Mensaje de error",
                    "type": "string",
                    "example": "Credenciales inválidas. Por favor, verifique su usuario y contraseña"
                }
            }
        },
        "entities.SwaggerLoginRequest": {
            "type": "object",
            "properties": {
                "contrasena": {
                    "description": "Contraseña del usuario",
                    "type": "string",
                    "example": "Abc123*"
                },
                "usuario": {
                    "description": "Usuario o correo electrónico",
                    "type": "string",
                    "example": "rodrigo.martinez"
                }
            }
        },
        "entities.SwaggerLoginResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "Correo electrónico del usuario (solo si se requiere verificación en dos pasos)",
                    "type": "string",
                    "example": "rodrigo.martinez@empresa.com"
                },
                "message": {
                    "description": "Mensaje informativo",
                    "type": "string",
                    "example": "Se ha enviado un código de verificación a su correo electrónico"
                },
                "require_two_factor": {
                    "description": "Indica si se requiere verificación en dos pasos",
                    "type": "boolean",
                    "example": true
                },
                "token": {
                    "description": "Token JWT si la autenticación es exitosa",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE0Mzc2NDEsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJ1c3VhcmlvIjoiUm9kcmlnbyJ9.-kQtpw4rfS5xFd9ZDvpGIHJw2ppvCgqIedWjCK-JZUs"
                }
            }
        },
        "entities.SwaggerPasswordResetRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "rodrigo.martinez@empresa.com"
                }
            }
        },
        "entities.SwaggerPasswordResetResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Se ha enviado un código de verificación a su correo electrónico"
                }
            }
        },
        "entities.SwaggerResetPasswordRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "847291"
                },
                "email": {
                    "type": "string",
                    "example": "rodrigo.martinez@empresa.com"
                },
                "new_password": {
                    "type": "string",
                    "example": "NuevaContraseña123*"
                }
            }
        },
        "entities.SwaggerResetPasswordResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Contraseña actualizada exitosamente"
                }
            }
        },
        "entities.SwaggerToggleTwoFactorRequest": {
            "type": "object",
            "properties": {
                "estado": {
                    "description": "Estado de la verificación en dos pasos",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "entities.SwaggerToggleTwoFactorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensaje informativo",
                    "type": "string",
                    "example": "La verificación en dos pasos ha sido activada exitosamente"
                }
            }
        },
        "entities.SwaggerVerifyCodeRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Código de verificación de 6 dígitos",
                    "type": "string",
                    "example": "847291"
                },
                "email": {
                    "description": "Correo electrónico del usuario",
                    "type": "string",
                    "example": "rodrigo.martinez@empresa.com"
                }
            }
        },
        "entities.SwaggerVerifyCodeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Mensaje informativo",
                    "type": "string",
                    "example": "Código verificado correctamente. Sesión iniciada."
                },
                "token": {
                    "description": "Token JWT si la verificación es exitosa",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE0Mzc2NDEsInJvbCI6ImFkbWluaXN0cmFkb3IiLCJ1c3VhcmlvIjoiUm9kcmlnbyJ9.-kQtpw4rfS5xFd9ZDvpGIHJw2ppvCgqIedWjCK-JZUs"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Introduce el token con el formato: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "API de Usuarios",
	Description:      "API para gestión de usuarios con autenticación en dos pasos y recuperación de contraseña.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
